import { Injectable } from '@angular/core';
import { Check } from '../models/check';
import { HttpClient, HttpParams } from '@angular/common/http';
import { Observable } from 'rxjs';

@Injectable({
  providedIn: 'root',
})
export class CheckserviceService {
  BaseUrl="https://sheetdb.io/api/v1/0d9sec81dzuqu";

  constructor(private http:HttpClient) { }

  ngOnInit():void{}

  getAll(): Observable<Check> {
    return this.http.get<Check>(this.BaseUrl)
  }
  
  getById(id: any): Observable<Check> { // Make sure the method name is getById
    const params = new HttpParams().set('id', id); // Set the ID parameter
    return this.http.get<Check>(this.BaseUrl+'/search', { params });
  }

  // getlistId(id: any): Check {
  //   return this.getlist().find(Checkid => Checkid.id == id)!;
  // }

  // getlist(): Check[] {
  //   return [

  //     {
  //       id: "TWITJ0001",
  //       name: 'Gudala Remanth Babu',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '20551A0579',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"

  //     },
  //     {
  //       id: "TWITJ0002",
  //       name: 'Vamsi Krishna Tatikonda',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '20551A4251',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering (AI/ML)"
  //     },
  //     {
  //       id: "TWITJ0003",
  //       name: 'Mani Darshini Tamalampudi',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '20551A0529',
  //       verified: true,
  //       tech: 'Active',
  //       gender: false,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITJ0004",
  //       name: 'Adigopula Naga Vasantha Rao',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '20551A0501',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITJ0005",
  //       name: 'Yashwanth Bondapalli',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '20551A0505',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITJ0006",
  //       name: 'Darbha Sai Venkata Abhiram ',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '20551A0506',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITJ0007",
  //       name: 'Guttula Lakshmi Sai Sneha',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '20551A0513',
  //       verified: true,
  //       tech: 'Active',
  //       gender: false,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITJ0008",
  //       name: 'K.Sai Venkat Jee',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '20551A0520',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },

  //     {
  //       id: "TWITJ0009",
  //       name: 'Hema Koteswari Kolakalapudi',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '20551A0521',
  //       verified: true,
  //       tech: 'Active',
  //       gender: false,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITJ0010",
  //       name: ' kolimi Sobha Rani',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '20551A0522',
  //       verified: true,
  //       tech: 'Active',
  //       gender: false,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITJ0011",
  //       name: 'K.Navya Sri',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '20551A0525',
  //       verified: true,
  //       tech: 'Active',
  //       gender: false,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITJ0012",
  //       name: 'Kurma Prakash',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '20551a0526',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITJ0013",
  //       name: 'Talagana Manohar',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '20551A0530',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITJ0014",
  //       name: 'M.Devi Harshitha ',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '20551A0535',
  //       verified: true,
  //       tech: 'Active',
  //       gender: false,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITJ0015",
  //       name: 'Panapana Shanmukha',
  //       Domain: 'Java FullStack',
  //       RollNo: '20551A0539',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITJ0016",
  //       name: 'Mukesh Polamarasetti',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '20551A0541',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITJ0017",
  //       name: 'Reetika Pulugu',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '20551A0544',
  //       verified: true,
  //       tech: 'Active',
  //       gender: false,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITJ0018",
  //       name: 'Manthena rithik varma',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '20551A0547',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITJ0019",
  //       name: 'Jagan Samsani',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '20551A0548',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },
    
  //     {
  //       id: "TWITJ0020",
  //       name: 'Krishna kanth',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '20551A0555',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITJ0021",
  //       name: 'Reddy Krishna Veni ',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '20551A05G4',
  //       verified: true,
  //       tech: 'Active',
  //       gender: false,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering"

  //     },
  //     {
  //       id: "TWITJ0022",
  //       name: 'Adina Divya Naga Jyothi',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '20551a0562',
  //       verified: true,
  //       tech: 'Active',
  //       gender: false,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITJ0023",
  //       name: 'Bandaru Madhuri',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '20551A0565',
  //       verified: true,
  //       tech: 'Active',
  //       gender: false,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITJ0024",
  //       name: 'Golthi.Sri Venkata Naga Ratna Vineetha',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '20551A0577',
  //       verified: true,
  //       tech: 'Active',
  //       gender: false,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering"
  //           },
      
  //     {
  //       id: "TWITJ0025",
  //       name: 'K.Navyasri',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '20551A0587',
  //       verified: true,
  //       tech: 'Active',
  //       gender: false,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITJ0026",
  //       name: 'Prudhvi Raj Karri',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '20551A0588',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITJ0027",
  //       name: 'Valluri Deepthi',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '20551A0553',
  //       verified: true,
  //       tech: 'Active',
  //       gender: false,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITJ0028",
  //       name: 'Korukonda Sirisha',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '20551A0593',
  //       verified: true,
  //       tech: 'Active',
  //       gender: false,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITJ0029",
  //       name: 'Ayaaz Ghalib Mohammad ',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '20551a0598',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITJ0030",
  //       name: 'Mohammad Shoaib',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '20551A0599',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITJ0031",
  //       name: 'Nakka Sandhya Bhargavi',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '20551A05A1',
  //       verified: true,
  //       tech: 'Active',
  //       gender: false,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITJ0032",
  //       name: 'B. V. N. Surya Prathap',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '20551A05C4',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITJ0033",
  //       name: 'Gadi veerendra',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '20551A05C8',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITJ0034",
  //       name: 'Godavarthi Taruni Chowdary ',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '20551A05D3',
  //       verified: true,
  //       tech: 'Active',
  //       gender: false,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITJ0035",
  //       name: 'Varshitha Ravada ',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '20551A05G3',
  //       verified: true,
  //       tech: 'Active',
  //       gender: false,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITJ0036",
  //       name: 'Bhavitha',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '20551A05G6',
  //       verified: true,
  //       tech: 'Active',
  //       gender: false,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITJ0037",
  //       name: 'T. Lakshmi Sahithi',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '20551A05H0',
  //       verified: true,
  //       tech: 'Active',
  //       gender: false,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITJ0038",
  //       name: 'Devnandan mahato',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '20551A0514',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITJ0039",
  //       name: 'Dadisetti Durga Bhanu Prakash',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '20551A4210',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering (AI/ML)"
        
  //     },
  //     {
  //       id: "TWITJ0040",
  //       name: 'Gedda Nithin Kumar',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '20551A4216',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering (AI/ML)"
  //     },
  //     {
  //       id: "TWITJ0041",
  //       name: 'Jakkula Annie Christi',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '20551A4223',
  //       verified: true,
  //       tech: 'Active',
  //       gender: false,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering (AI/ML)"
  //     },
  //     {
  //       id: "TWITJ0042",
  //       name: 'Manduri Revathi',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '20551A4234',
  //       verified: true,
  //       tech: 'Active',
  //       gender: false,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering (AI/ML)"
  //     },
  //     {
  //       id: "TWITJ0043",
  //       name: 'Sannikanti NikhithaSri',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '20551A4248',
  //       verified: true,
  //       tech: 'Active',
  //       gender: false,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering (AI/ML)"
  //     },
  //     {
  //       id: "TWITJ0044",
  //       name: 'Vuppala Satya Sandeep',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '20551A4256',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering (AI/ML)"
  //     },
  //     {
  //       id: "TWITJ0045",
  //       name: 'Vengisetty Nagendra Kumar ',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '20551A4255',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering (AI/ML)"
  //     },
  //     {
  //       id: "TWITJ0046",
  //       name: 'Yarnagula srinivas jagadeesh ',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '20551A4258',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering (AI/ML)"
  //     },
  //     {
  //       id: "TWITJ0047",
  //       name: 'Podalakoori Hemanth Kumar',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '20551A4261',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering (AI/ML)"
  //     },
  //     {
  //       id: "TWITJ0048",
  //       name: 'Arevarapu Nagalakshmi ',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '21555A0501',
  //       verified: true,
  //       tech: 'Active',
  //       gender: false,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITJ0049",
  //       name: 'Supraja Bonagiri',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '21555A0502',
  //       verified: true,
  //       tech: 'Active',
  //       gender: false,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITJ0050",
  //       name: 'Bonthu Chaitanya Mouli ',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '21555A0503',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITJ0051",
  //       name: 'Kariminji Hemalatha',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '21555A0508',
  //       verified: true,
  //       tech: 'Active',
  //       gender: false,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITJ0052",
  //       name: 'Katta Veerababu ',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '21555A0509',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITJ0053",
  //       name: 'M.Lavanya',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '21555A0516',
  //       verified: true,
  //       tech: 'Active',
  //       gender: false,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITJ0054",
  //       name: 'Subrahmanyam Vallabhaneni',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '21555A0521',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITJ0055",
  //       name: 'Alla Karthik',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '21555A4201',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering (AI/ML)"
  //     },
  //     {
  //       id: "TWITJ0056",
  //       name: 'Vudimudi Rithvik Varma',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '21555A4204',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering (AI/ML)"
  //     },
  //     {
  //       id: "TWITJ0057",
  //       name: 'Sathya Sai Ganesh Yerramsetti',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '21555A4205',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering (AI/ML)"
  //     },
  //     {
  //       id: "TWITJ0058",
  //       name: 'V Dileep Sai Chandra ',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '22555A0516',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITJ0059",
  //       name: 'Chandanada Krishna',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '21555A0504',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITJ0060",
  //       name: 'Shree Krishna Kumar Prajapati ',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '20551A05I3',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"

  //     },
  //     {
  //       id: "TWITJ0061",
  //       name: 'Padala Siva Kumari',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '20551A0538',
  //       verified: true,
  //       tech: 'Active',
  //       gender: false,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITJ0062",
  //       name: 'Ganireddy Durga Prasad',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '21555A0505',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITJ0063",
  //       name: 'Adigopula Venkateswara Rao',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '20551A0502',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITJ0064",
  //       name: 'Sai Sudheer Kethapalli',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '20551A0591',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITJ0065",
  //       name: 'Prathipati Chandu',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '20551A0543',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },

  //     // junior JFS

  //     {
  //       id: "TWITJ0066",
  //       name: 'Sundarapalli Sai ',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '21551A0453',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Electronics And Communication Engineering"
  //     },
  //     {
  //       id: "TWITJ0067",
  //       name: 'G.Ashok',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '21551A0415',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Electronics And Communication Engineering"
  //     },
  //     {
  //       id: "TWITJ0068",
  //       name: 'Makka Veera Lakshmi Sai Rishitha',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '21551A0426',
  //       verified: true,
  //       tech: 'Active',
  //       gender: false,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Electronics And Communication Engineering"
  //     },
  //     {
  //       id: "TWITJ0069",
  //       name: 'Nagumalla Prasanna Lakshmi ',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '21551A0433',
  //       verified: true,
  //       tech: 'Active',
  //       gender: false,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Electronics And Communication Engineering"
  //     },
  //     {
  //       id: "TWITJ0070",
  //       name: 'P.Suvarna kumari',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '21551A0437',
  //       verified: true,
  //       tech: 'Active',
  //       gender: false,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Electronics And Communication Engineering"
  //     },
  //     {
  //       id: "TWITJ0071",
  //       name: 'Kollepara Bhavya likhita ',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '21551A0597',
  //       verified: true,
  //       tech: 'Active',
  //       gender: false,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITJ0072",
  //       name: 'Manugula Eswara Sai Vamsi Rama Prakash ',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '21551A05A6',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },

  //     {
  //       id: "TWITJ0073",
  //       name: 'Bommireddi M Ganapathi Satyadurgaprasad ',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '21551A4206',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering (CSM)"
  //     },
  //     {
  //       id: "TWITJ0074",
  //       name: 'Boyana Venkata Vyshnavi Lakshmi',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '21551A4207',
  //       verified: true,
  //       tech: 'Active',
  //       gender: false,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering (CSM)"
  //     },
  //     {
  //       id: "TWITJ0075",
  //       name: 'Garikina Balaji',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '21551A4212',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering (CSM)"
  //     },
  //     {
  //       id: "TWITJ0076",
  //       name: 'Geethika Ravipati',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '21551A4213',
  //       verified: true,
  //       tech: 'Active',
  //       gender: false,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering (CSM)"
  //     },
  //     {
  //       id: "TWITJ0077",
  //       name: 'Jawadi Shanmuk Sai Vardhan',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '21551A4218',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering (CSM)"
  //     },
  //     {
  //       id: "TWITJ0078",
  //       name: 'Kaarem Dinisha ',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '21551A4219',
  //       verified: true,
  //       tech: 'Active',
  //       gender: false,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering (CSM)"
  //     },
  //     {
  //       id: "TWITJ0079",
  //       name: 'Kesavarapu Bhadra Lakshmi Alekhya',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '21551A4223',
  //       verified: true,
  //       tech: 'Active',
  //       gender: false,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering (CSM)"
  //     },
  //     {
  //       id: "TWITJ0080",
  //       name: 'Kuramapu Sai Soudamini',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '21551A4229',
  //       verified: true,
  //       tech: 'Active',
  //       gender: false,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering (CSM)"
  //     },
  //     {
  //       id: "TWITJ0081",
  //       name: 'Maddukuri Sai Teja ',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '21551A4231',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering (CSM)"
  //     },
  //     {
  //       id: "TWITJ0082",
  //       name: 'Praneeth mopidevi ',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '21551A4237',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering (CSM)"
  //     },
  //     {
  //       id: "TWITJ0083",
  //       name: 'Sriramula Brahmachary',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '21551A4250',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"22-05-2023 to 17-06-2023" ,
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering (CSM)"
  //     },
  //     {
  //       id: "TWITJ0084",
  //       name: 'Tella Sai Rahul ',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '21551A4252',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering (CSM)"
  //     },
  //     {
  //       id: "TWITJ0085",
  //       name: 'Bathina Madhuri CRT',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '21551A4601',
  //       verified: true,
  //       tech: 'Active',
  //       gender: false,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering (CSC)"
  //     },
  //     {
  //       id: "TWITJ0086",
  //       name: 'Katari Meghana',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '21551A4606',
  //       verified: true,
  //       tech: 'Active',
  //       gender: false,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering (CSC)"
  //     },
  //     {
  //       id: "TWITJ0087",
  //       name: 'Lakkanaboina Revathi',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '21551A4618',
  //       verified: true,
  //       tech: 'Active',
  //       gender: false,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering (CSC)"
  //     },
  //     {
  //       id: "TWITJ0088",
  //       name: 'Mungi Durga Sirisha ',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '22555A4206',
  //       verified: true,
  //       tech: 'Active',
  //       gender: false,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering (CSM)"
  //     },
  //     {
  //       id: "TWITJ0089",
  //       name: 'Sri Hari',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '21551A4641',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering (CSC)"
  //     },
  //     {
  //       id: "TWITJ0090",
  //       name: 'B Surekha',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '22555A4207',
  //       verified: true,
  //       tech: 'Active',
  //       gender: false,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering (CSM)"
  //     },
  //     {
  //       id: "TWITJ0091",
  //       name: 'A khanishma',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '22555A4603',
  //       verified: true,
  //       tech: 'Active',
  //       gender: false,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"she",
  //       user:"his",
  //       branch:"Computer Science And Engineering (CSC)"
  //     },
  //     {
  //       id: "TWITJ0092",
  //       name: 'Sontyana Jagan',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '22555A4606',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering (CSC)"
        
  //     },
  //     {
  //       id: "TWITJ0093",
  //       name: 'J.Tharun',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '22555A4607',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering (CSC)"
  //     },
  //     {
  //       id: "TWITJ0094",
  //       name: 'Mande Ram Naga Venkata Akhil',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '22555A4608',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering (CSC)"
  //     },
  //     {
  //       id: "TWITJ0095",
  //       name: 'Kovvuri Tanusha',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '21551A4226',
  //       verified: true,
  //       tech: 'Active',
  //       gender: false,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering (CSM)"
  //     },
  //     {
  //       id: "TWITJ0096",
  //       name: 'R.Ravi Chand',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '21551A4244',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering (CSM)"
  //     },
  //     {
  //       id: "TWITJ0097",
  //       name: 'Y.Sumanth',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '22555A4609',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering (CSC)"
  //     },
  //     {
  //       id: "TWITJ0000",
  //       name: 'Y.Sumanth',
  //       Domain: 'Java FullStack and ui/ux designing',
  //       RollNo: '22555A4609',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering (CSC)"
  //     },
  //     {
  //       id: "TWITA0098",
  //       name: 'chanta phani chandana',
  //       Domain: 'amazon web service',
  //       RollNo: '22555A4608',
  //       verified: true,
  //       tech: 'Active',
  //       gender: false,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering"
  //     },

  //     {
  //       id: "TWITA0099",
  //       name: 'Chadalavada Joyley',
  //       Domain: 'amazon web service',
  //       RollNo: '21551A0570',
  //       verified: true,
  //       tech: 'Active',
  //       gender: false,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering"

  //     },
  //     {
  //       id: "TWITA0100",
  //       name: 'Chittsari Sri Raja Vishnu Vardhan',
  //       Domain: 'amazon web service',
  //       RollNo: '21551A0572 ',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITA0101",
  //       name: 'K Charles Antony',
  //       Domain: 'amazon web service',
  //       RollNo: '21551A0512',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITA0102",
  //       name: 'R.Vinay',
  //       Domain: 'amazon web service',
  //       RollNo: '22555A0526',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITA0103",
  //       name: 'D. Vinod kumar',
  //       Domain: 'amazon web service',
  //       RollNo: '21551A0578',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITA0104",
  //       name: 'Reddy Rakesh',
  //       Domain: 'amazon web service',
  //       RollNo: '21551A04B8',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Electronics And Communication Engineering"
  //     },
  //     {
  //       id: "TWITA0105",
  //       name: 'Bairi Karthik',
  //       Domain: 'amazon web service',
  //       RollNo: '21551A0511',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITA0106",
  //       name: 'D.Sai Naresh',
  //       Domain: 'amazon web service',
  //       RollNo: '21551A0522',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITA0107",
  //       name: 'Guttula kiran',
  //       Domain: 'amazon web service',
  //       RollNo: '21551A0531',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITA0108",
  //       name: 'Karri Jansi',
  //       Domain: 'amazon web service',
  //       RollNo: '21551A0535',
  //       verified: true,
  //       tech: 'Active',
  //       gender: false,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITA0109",
  //       name: 'Lankalapalli Simhadri',
  //       Domain: 'amazon web service',
  //       RollNo: '21551A0539',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITA0110",
  //       name: 'Mannepalli Kumar',
  //       Domain: 'amazon web service',
  //       RollNo: '21551A0541',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITA0111",
  //       name: 'M.Dhilleswar rao',
  //       Domain: 'amazon web service',
  //       RollNo: '21551A0543',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITA0112",
  //       name: 'P.Harlica',
  //       Domain: 'amazon web service',
  //       RollNo: '21551A0547',
  //       verified: true,
  //       tech: 'Active',
  //       gender: false,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering"
  //     },

  //     {
  //       id: "TWITA0113",
  //       name: 'Undela Murali',
  //       Domain: 'amazon web service',
  //       RollNo: '21551A0561',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITA0114",
  //       name: 'Vangalapudi Ajay ',
  //       Domain: 'amazon web service',
  //       RollNo: '21551A0562',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITA0115",
  //       name: 'B.Eesha Sharvi',
  //       Domain: 'amazon web service',
  //       RollNo: '21551A0569',
  //       verified: true,
  //       tech: 'Active',
  //       gender: false,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITA0116",
  //       name: 'Chittela Mahesh ',
  //       Domain: 'amazon web service',
  //       RollNo: '21551A0573',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITA0117",
  //       name: 'Dasari Dheeraj Tapan ',
  //       Domain: 'amazon web service',
  //       RollNo: '21551A0574',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITA0118",
  //       name: 'Devi Satya Abhiram Samsani',
  //       Domain: 'amazon web service',
  //       RollNo: '21551A0577',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITA0119",
  //       name: 'G.Yugesh',
  //       Domain: 'amazon web service',
  //       RollNo: '21551A0582',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITA0120",
  //       name: 'Gonnabathula Praveen Venkata Raju',
  //       Domain: 'amazon web service',
  //       RollNo: '21551A0585',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },

  //     {
  //       id: "TWITA0121",
  //       name: 'Illa Kumar Chandra ',
  //       Domain: 'amazon web service',
  //       RollNo: '21551A0587',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITA0122",
  //       name: 'Pavan Krishna kagitha',
  //       Domain: 'amazon web service',
  //       RollNo: '21551A0589',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITA0123",
  //       name: 'Kamidi Jagadeesh ',
  //       Domain: 'amazon web service',
  //       RollNo: '21551A0591',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITA0124",
  //       name: 'Sai Krishna Kasimalla ',
  //       Domain: 'amazon web service',
  //       RollNo: '21551A0593',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITA0125",
  //       name: 'K Srija',
  //       Domain: 'amazon web service',
  //       RollNo: '21551A05A0',
  //       verified: true,
  //       tech: 'Active',
  //       gender: false,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering"
  //     },

  //     {
  //       id: "TWITA0126",
  //       name: 'N.Kunal',
  //       Domain: 'amazon web service',
  //       RollNo: '21551A05A1',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITA0127",
  //       name: 'Durga Manishwar ',
  //       Domain: 'amazon web service',
  //       RollNo: '21551A05A3',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITA0128",
  //       name: 'Meheboob Dafia Anjum',
  //       Domain: 'amazon web service',
  //       RollNo: '21551A05A7',
  //       verified: true,
  //       tech: 'Active',
  //       gender: false,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITA0129",
  //       name: 'Nalla Avanthika ',
  //       Domain: 'amazon web service',
  //       RollNo: '21551A05B0',
  //       verified: true,
  //       tech: 'Active',
  //       gender: false,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITA0130",
  //       name: 'Pradeep Kumar Nalluri',
  //       Domain: 'amazon web service',
  //       RollNo: '21551A05B1',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITA0131",
  //       name: 'N.v v Sai Kumar',
  //       Domain: 'amazon web service',
  //       RollNo: '21551A05B3',
  //       verified: true,
  //       tech: 'Active',
  //       gender: true,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },


  //     {
  //       id: "TWITA0132",
  //       name: 'Paluri Dhanyasri Ratna Mounika',
  //       Domain: 'amazon web service',
  //       RollNo: '21551A05B6',
  //       verified: true,
  //       tech: 'Active',
  //       gender:false,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITA0133",
  //       name: 'Pulavarthi Sai Lokesh',
  //       Domain: 'amazon web service',
  //       RollNo: '21551A05B7',
  //       verified: true,
  //       tech: 'Active',
  //       gender:true,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITA0134",
  //       name: 'Purushotham Venkata Krishna',
  //       Domain: 'amazon web service',
  //       RollNo: '21551A05B8',
  //       verified: true,
  //       tech: 'Active',
  //       gender:true,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITA0135",
  //       name: 'Ravada Srikanth',
  //       Domain: 'amazon web service',
  //       RollNo: '21551A05B9',
  //       verified: true,
  //       tech: 'Active',
  //       gender:true,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITA0136",
  //       name: 'Ajay Pradeep Siraparapu',
  //       Domain: 'amazon web service',
  //       RollNo: '21551A05C1',
  //       verified: true,
  //       tech: 'Active',
  //       gender:true,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITA0137",
  //       name: 'S.Venkatesh',
  //       Domain: 'amazon web service',
  //       RollNo: '21551A05C2',
  //       verified: true,
  //       tech: 'Active',
  //       gender:true,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITA0138",
  //       name: 'Tadepalli Sri Haripriya',
  //       Domain: 'amazon web service',
  //       RollNo: '21551A05C3 ',
  //       verified: true,
  //       tech: 'Active',
  //       gender:false,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering"
  //     },


  //     {
  //       id: "TWITA0139",
  //       name: 'Akula Ashish Kumar',
  //       Domain: 'amazon web service',
  //       RollNo: '22555A0530',
  //       verified: true,
  //       tech: 'Active',
  //       gender:true,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITA0140",
  //       name: 'Vannemreddi Lakshmi Radha Pavan',
  //       Domain: 'amazon web service',
  //       RollNo: '21551A05C6',
  //       verified: true,
  //       tech: 'Active',
  //       gender:true,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITA0141",
  //       name: 'Vegesna Joshnavi',
  //       Domain: 'amazon web service',
  //       RollNo: '21551A05C8',
  //       verified: true,
  //       tech: 'Active',
  //       gender:false,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITA0142",
  //       name: 'Sachit',
  //       Domain: 'amazon web service',
  //       RollNo: '21551A05D3',
  //       verified: true,
  //       tech: 'Active',
  //       gender:true,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITA0143",
  //       name: 'Chitrapu Pradeep Kumar',
  //       Domain: 'amazon web service',
  //       RollNo: '21551A05E1',
  //       verified: true,
  //       tech: 'Active',
  //       gender:true,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITA0144",
  //       name: 'Gangireddy Pavan Kumar Reddy ',
  //       Domain: 'amazon web service',
  //       RollNo: '21551A05E6',
  //       verified: true,
  //       tech: 'Active',
  //       gender:true,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITA0145",
  //       name: 'Korada Ravi Kumar',
  //       Domain: 'amazon web service',
  //       RollNo: '21551A05E9',
  //       verified: true,
  //       tech: 'Active',
  //       gender:true,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITA0146",
  //       name: 'Venkata Satya Rupesh Burlagadda ',
  //       Domain: 'amazon web service',
  //       RollNo: '21551A05H8',
  //       verified: true,
  //       tech: 'Active',
  //       gender:true,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITA0147",
  //       name: 'Panchadi Geethanjali',
  //       Domain: 'amazon web service',
  //       RollNo: '21551A0548',
  //       verified: false,
  //       tech: 'Active',
  //       gender:true,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITA0148",
  //       name: 'Vytla S Y Veera Venkata Satyanarayana',
  //       Domain: 'amazon web service',
  //       RollNo: '21551A0581',
  //       verified: true,
  //       tech: 'Active',
  //       gender:true,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITA0149",
  //       name: 'Kota Deepesh',
  //       Domain: 'amazon web service',
  //       RollNo: '21551A4224',
  //       verified: true,
  //       tech: 'Active',
  //       gender:true,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering (CSM)"
  //     },
  //     {
  //       id: "TWITA0150",
  //       name: 'Mogalapalli Harika',
  //       Domain: 'amazon web service',
  //       RollNo: '21551A4609',
  //       verified: true,
  //       tech: 'Active',
  //       gender:false,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering (CSC)"
  //     },
  //     {
  //       id: "TWITA0151",
  //       name: 'Koda Madhuri',
  //       Domain: 'amazon web service',
  //       RollNo: '21551A4653',
  //       verified: true,
  //       tech: 'Active',
  //       gender:false,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering (CSC)"
  //     },
  //     {
  //       id: "TWITA0152",
  //       name: 'CH. Krishna Sai',
  //       Domain: 'amazon web service',
  //       RollNo: '21551A4645',
  //       verified: true,
  //       tech: 'Active',
  //       gender:true,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering (CSC)"
  //     },
  //     {
  //       id: "TWITA0153",
  //       name: 'P Surya Teja',
  //       Domain: 'amazon web service',
  //       RollNo: '22555A0505',
  //       verified: true,
  //       tech: 'Active',
  //       gender:true,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITA0154",
  //       name: 'CH. Satya Veni',
  //       Domain: 'amazon web service',
  //       RollNo: '22555A0507',
  //       verified: true,
  //       tech: 'Active',
  //       gender:false,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITA0155",
  //       name: 'G. Mohana Akhila',
  //       Domain: 'amazon web service',
  //       RollNo: '21551A4623',
  //       verified: true,
  //       tech: 'Active',
  //       gender:false,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering (CSC)"
  //     },
  //     {
  //       id: "TWITA0156",
  //       name: 'K.Pavani',
  //       Domain: 'amazon web service',
  //       RollNo: '22555A0510',
  //       verified: true,
  //       tech: 'Active',
  //       gender:false,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITA0157",
  //       name: 'I.D.S. Bobby',
  //       Domain: 'amazon web service',
  //       RollNo: '21551A05A8',
  //       verified: true,
  //       tech: 'Active',
  //       gender:true,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
        
  //     },


  //     {
  //       id: "TWITA0158",
  //       name: 'Karthik Yedula',
  //       Domain: 'amazon web service',
  //       RollNo: '22555A0518',
  //       verified: true,
  //       tech: 'Active',
  //       gender:true,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITA0159",
  //       name: 'Vasa Gopi',
  //       Domain: 'amazon web service',
  //       RollNo: '22555A0528',
  //       verified: true,
  //       tech: 'Active',
  //       gender:true,
  //       date:"22-05-2023 to 17-06-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITA0160",
  //       name: 'Achanta phani chandana ',
  //       Domain: 'amazon web service',
  //       RollNo: '20551A04C8',
  //       verified: true,
  //       tech: 'Active',
  //       gender:false,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Electronics And Communication Engineering"
  //     },
  //     {
  //       id: "TWITA0161",
  //       name: 'Ganta Surya Deepthi',
  //       Domain: 'amazon web service',
  //       RollNo: '20551A0510',
  //       verified: true,
  //       tech: 'Active',
  //       gender:false,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITA0162",
  //       name: 'Irugula Sri Sai Bhavya',
  //       Domain: 'amazon web service',
  //       RollNo: '20551A0514',
  //       verified: true,
  //       tech: 'Active',
  //       gender:false,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITA0163",
  //       name: 'Nulu Mohitha Chandra Sai Amrutha',
  //       Domain: 'amazon web service',
  //       RollNo: '20551A0537',
  //       verified: true,
  //       tech: 'Active',
  //       gender:false,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITA0164",
  //       name: 'Gandham Roshitha Madhuri',
  //       Domain: 'amazon web service',
  //       RollNo: '20551A0576 ',
  //       verified: true,
  //       tech: 'Active',
  //       gender:false,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITA0165",
  //       name: 'Anitha Kandukuri',
  //       Domain: 'amazon web service',
  //       RollNo: '20551A0586',

  //       verified: true,
  //       tech: 'Active',
  //       gender:false,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering"
       
  //     },
  //     {
  //       id: "TWITA0166",
  //       name: 'Kesarapalli Santhi Kumari',
  //       Domain: 'amazon web service',
  //       RollNo: '20551A0589',

  //       verified: true,
  //       tech: 'Active',
  //       gender:false,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITA0167",
  //       name: 'Neechu Swetha',
  //       Domain: 'amazon web service',
  //       RollNo: '20551A05A2',

  //       verified: true,
  //       tech: 'Active',
  //       gender:false,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITA0168",
  //       name: 'Pinipe Navya Sri',
  //       Domain: 'amazon web service',
  //       RollNo: '20551A05A5',

  //       verified: true,
  //       tech: 'Active',
  //       gender:false,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITA0169",
  //       name: 'Renuka Yadlapalli',
  //       Domain: 'amazon web service',
  //       RollNo: '20551A05B5',
  //       verified: true,
  //       tech: 'Active',
  //       gender:false,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITA0170",
  //       name: 'Rampa Aditya Raghava Koundinya',
  //       Domain: 'amazon web service',
  //       RollNo: '20551A4646 ',
  //       verified: true,
  //       tech: 'Active',
  //       gender:true,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering (CSC)"
  //     },
  //     {
  //       id: "TWITA0171",
  //       name: 'G.Jyothsna Jasmine',
  //       Domain: 'amazon web service',
  //       RollNo: '20551A0512',
  //       verified: false,
  //       tech: 'Active',
  //       gender:true,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITA0172",
  //       name: 'Namala Devisri',
  //       Domain: 'amazon web service',
  //       RollNo: '21551A05B2',
  //       verified: true,
  //       tech: 'Active',
  //       gender:false,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITA0173",
  //       name: 'Jillella Akshaya Prajwala',
  //       Domain: 'amazon web service',
  //       RollNo: '21551A0588',
  //       verified: true,
  //       tech: 'Active',
  //       gender:false,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITA0174",
  //       name: 'Gudapati Bala Gayathri',
  //       Domain: 'amazon web service',
  //       RollNo: '21551A0586',
  //       verified: true,
  //       tech: 'Active',
  //       gender:false,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"she",
  //       user:"her",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITA0175",
  //       name: 'M Arjun Kumar',
  //       Domain: 'amazon web service',
  //       RollNo: '21551A4236',
  //       verified: true,
  //       tech: 'Active',
  //       gender:true,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     },
  //     {
  //       id: "TWITA0176",
  //       name: 'Preetish Madhu',
  //       Domain: 'amazon web service',
  //       RollNo: '20551A4645',
  //       verified: true,
  //       tech: 'Active',
  //       gender:true,
  //       date:"15-05-2023 to 08-07-2023",
  //       type:"he",
  //       user:"his",
  //       branch:"Computer Science And Engineering"
  //     }
  //   ];
  // }
}
